### Тема: Решение систем линейных уравнений
#### Выполнил: Джугели Дмитрий Александрович (ИВТ-23) (d_d_a_37@mail.ru)
#### Преподаватель: Гурьянов М.А., кафедра ВМ-1
#### Лабораторная работа №7, Вариант 10.
#### Весенний семестр, 2022 год
#### МИЭТ, Зеленоград

### 1. Теоретическая справка

Пусть требуется найти решение системы
$$
\begin{cases}
   \ a_{11}x_1+a_{12}x_2+...a_{1n}x_n=f_1, 
   \\
  \ a_{21}x_1+a_{22}x_2+...a_{2n}x_n=f_2,
   \\
   ...
   \\
  \ a_{n1}x_1+a_{n2}x_2+...a_{nn}x_n=f_n
 \end{cases}
$$


Мы будем считать, что $∆ = detA \neq 0$, то есть решение существует
и единственно.




####Число обусловленности
Характер задачи и точность получаемого решения в большой степени зависят от ее обусловленности, являющейся важнейшим математическим понятием, влияющим на выбор метода ее решения. Поясним это понятие на примере двумерной задачи: 
$$
\begin{cases}
   \ a_{11}x_1+a_{12}*x_2=b_1,
   \\
  \ a_{21}x_1+a_{22}x_2=b_2.
 \end{cases}
$$
Точным решением этой задачи является вектор $x_∗=(x_{∗1},x_{∗2})^T$
, компоненты которого определяются координатами точки пересечения двух прямых, соответствующих уравнениям $a_{11}x_1+a_{12}*x_2=b_1$ , $
 a_{21}x_1+a_{22}x_2=b_2$.

Более строго обусловленность задачи характеризуется числом обусловленности $ν(A)=∥A∥⋅∥A−1∥$
, где $∥A∥$ - норма матрицы A
, а $∥A−1∥$ - норма обратной матрицы. Чем больше это число, тем хуже обусловленность системы (при $ν(A)≈10^3÷10^4$
 система линейных алгебраических уравнений плохо обусловлена). В качестве нормы матрицы может быть принято число, являющееся максимальным из сумм (по модулю) элементов всех строк этой матрицы. Подчеркнем, что реализация хорошей или плохой обусловленности в корректной и некорректной задачах напрямую связана с вытекающей отсюда численной устойчивостью или неустойчивостью. При этом для решения некорректных задач обычно применяются специальные методы или математические преобразования этих задач к корректным.

В численном анализе используются два класса численных методов решения систем линейных алгебраических уравнений:
* Прямые методы, позволяющие найти решение за определенное число операций. К прямым методам относятся: метод Гаусса и его модификации (в том числе метод прогонки), метод LU
 — разложения и др.

 
* Итерационные методы, основанные на использовании повторяющегося (циклического) процесса и позволяющие получить решение в результате последовательных приближений. Операции, входящие в повторяющийся процесс, составляют итерацию. К итерационным методам относятся: метод простых итераций, метод Зейделя и др.

### 2. Постановка задачи
**Ход работы:**

1. Задайте матрицу A и вектор-столбец f системы линейных уравнений
$AX = f$, используя генератор случайных чисел. Очевидно, можно получить решение таким образом: $X = A^{−1}f$ (предварительно проверив,
что матрица A не вырожденная) или по правилу Крамера ($x_i =\frac{det A_i}{det A}$
,
где $A_i$ — матрица, получающаяся из матрицы A заменой i-го столбца на
столбец правой части $f$). Реализуйте и проверьте работоспособность этих
методов. Несмотря на простоту использования в Matlab, эти варианты
чрезвычайно неэкономичны по числу операций.

2. Напишите программу нахождения решения системы линейных уравнений методом Гаусса с выбором главного элемента.

3.  Задайте случайным образом матрицу A размерности $20 × 20$ и вектор X. Определите число обусловленности матрицы A с помощью функции cond. Изменяя значения некоторых элементов матрицы A, добейтесь,
чтобы её число обусловленности стало больше $10^3$
. Используя A и X, найдите вектор $f = AX$. Полагая вектор X неизвестным, решите систему
линейных уравнений всеми предложенными выше методами и сравните
найденные решения с уже известным. Какой из методов дал более точный
результат? Обратите внимание на решения, полученные обычным методом
Гаусса и методом с выбором главного элемента.

## 3. Предполагаемое решение и его точность

В качестве **входных параметров** используются:

* Двумерная матрица $А$ и вектор значений $f$


**Результатом** работы является:

* Вектор значений решения СЛАУ $X$


#4. Программная реализация

1

In [10]:
import numpy as np
rows = 3
cols = 3
#input matrix
def A_rand(rows, cols):
  A = np.random.rand(rows,cols)*10
#check det
  while True:
    if(np.linalg.det(A) == 0):
      A = np.random.randint(rows,cols)
    else:
      break
  return A      
A = A_rand(rows, cols)      
F = np.random.rand(rows,1)*10 
print("Maatrix A :\n",A)
print("Vector :\n",F)

Maatrix A :
 [[5.01706468 8.51936214 0.76783158]
 [3.93351143 0.52297589 0.24655064]
 [7.7121496  6.41976713 9.23393839]]
Vector :
 [[1.95642386]
 [0.48589155]
 [6.31950319]]


In [11]:
#Revert matrix
X1 = np.linalg.inv(A).dot(F)
print("Return : ",X1)

Return :  [[0.07189933]
 [0.13979292]
 [0.52713876]]


In [13]:
#Krammer's method
def kram(A,F,rows,cols):
  de10 = np.linalg.det(A)
  dels = []
  A_del = A.copy()
  for num_col in range(0,cols):
    for row in range(0,rows):
      A_del[row][num_col] = F[row][0]
    dels.append(np.linalg.det(A_del))
    A_del = A.copy()
  print("Return : ",dels/de10)  
  return dels/de10
X2 = kram(A,F,rows,cols)


Return :  [0.07189933 0.13979292 0.52713876]


##2  Напишите программу нахождения решения системы линейных уравнений методом Гаусса с выбором главного элемента.

In [15]:
#Gaus's method
def gauss(A,F,rows,cols):
  A_ = np.concatenate((A.copy(),F.copy()),axis=1)
  sol = []
  for row in range(0,rows):
    elem = []
    index = []
    for curRow in range(row,rows):
      elem.append(A_[curRow,row])
      index.append(curRow)
    curMaxRow = index[elem.index(max(elem))]

    buff = A_[row].copy()
    A_[row] = A_[curMaxRow].copy()
    A_[curMaxRow] = buff.copy()
    A_[row] = A_[row].copy() / A_[row][row]

    for curRow in range(row+1,rows):
      A_[curRow] = A_[curRow].copy() - (A_[row].copy() * A_[curRow][row].copy())  
  sol.append(A_[-1][-1])
  
  for row in range(-rows+2,1):
    curSol = A_[-row][-1]
    curr = 0

    for i in range(-row+1,rows):
      curSol = curSol - (A_[-row][i] * sol[curr])
      curr+=1

    sol.reverse()
    sol.append(curSol)
    sol.reverse()

  print("Return : ",sol)
  return sol
X3=gauss(A,F,rows,cols)

Return :  [0.07189932586463443, 0.13979291937082317, 0.5271387610045368]


### 3 Задайте случайным образом матрицу A размерности $20 × 20$ и вектор X. 
Определите число обусловленности матрицы A с помощью функции cond. Изменяя значения некоторых элементов матрицы A, добейтесь,
чтобы её число обусловленности стало больше $10^3$
. Используя A и X, найдите вектор $f = AX$. Полагая вектор X неизвестным, решите систему
линейных уравнений всеми предложенными выше методами и сравните
найденные решения с уже известным. Какой из методов дал более точный
результат? Обратите внимание на решения, полученные обычным методом
Гаусса и методом с выбором главного элемента.

In [17]:
#20x20
rows=20
cols=20
A = A_rand(rows, cols)      
F = np.random.rand(rows,1)*10 

A_copy = A.copy()
cd = np.linalg.cond(A_copy)
print("First value = ",cd)

i = 1
while True:
  if cd <= 1000:
    for row in range(0,rows):
      A_copy[row][i] = 1
    cd = np.linalg.cond(A_copy)
    print(f"Value obuslovlennosti № {i} = {cd}")
    i+=1
  else: 
    print("The number of obuslovlennost is more than the 1000.")
    break




First value =  388.58622937080804
Value obuslovlennosti № 1 = 935.9191554328421
Value obuslovlennosti № 2 = 2.407477688904331e+16
The number of obuslovlennost is more than the 1000.


In [18]:

X1 = np.linalg.inv(A).dot(F)
print("Method of rever matrix")
print("Return: ",X1)
print("Gaus's method")
gauss(A,F,rows,cols)
print("Kramer's method")
X2 = kram(A,F,rows,cols)

Method of rever matrix
Return:  [[ 4.83712056]
 [ 6.65740267]
 [ 2.35444746]
 [-2.63310368]
 [ 3.71867051]
 [-0.80117318]
 [-1.03036171]
 [-2.88625578]
 [-2.92682128]
 [-0.17926541]
 [-5.81849631]
 [ 1.04351355]
 [-4.73689497]
 [-0.29131236]
 [-2.9418592 ]
 [-0.03728595]
 [ 9.16967061]
 [ 3.81760664]
 [-6.30370935]
 [-0.20480287]]
Gaus's method
Return :  [4.83712055921544, 6.657402667838626, 2.3544474586565065, -2.6331036828447854, 3.718670512292989, -0.8011731778080801, -1.0303617141817385, -2.8862557823093655, -2.9268212832956597, -0.1792654080634294, -5.818496311566086, 1.0435135538080629, -4.736894972496655, -0.29131236125836046, -2.941859201983044, -0.03728594610024505, 9.16967061345872, 3.8176066387790364, -6.303709351780464, -0.20480286664270653]
Kramer's method
Return :  [ 4.83712056  6.65740267  2.35444746 -2.63310368  3.71867051 -0.80117318
 -1.03036171 -2.88625578 -2.92682128 -0.17926541 -5.81849631  1.04351355
 -4.73689497 -0.29131236 -2.9418592  -0.03728595  9.16967061  3.